name: Feature
description: Propose a new feature (user-facing)
title: "feat: "
labels: ["type: feature"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What do we want to achieve and for whom?
      placeholder: "As a <user>, I want <goal> so that <benefit>."
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Checklist of what must be true for this to be done.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes / context
      description: Links, references, decisions, screenshots, etc.
    validations:
      required: false
